services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest  # removed container_name
    restart: always
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak-network
    command:
      - start
      - --http-enabled=true
      - --proxy-headers=xforwarded

  keycloak_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: ${COMPOSE_PROJECT_NAME:-keycloak}-network
    driver: bridge

volumes:
  postgres_data: